# Pandas

Pandas is an open source library which provides high-performance, easy-to-use data structures and data analysis tools for the Python programming language. Pandas has a lot of functions that will help in reading and writing data and also for data manipulation. Thus we will be using pandas throughout the course.


#Pandas Dataframes
DataFrame is an object for data manipulation. You can think of it as a 2D tabular structure, where every row is a dataset entry and columns represents features of data.

Creating copy of DataFrame

df = iris 

Above statement simply makes df refer to the data frame object that iris is referring to. So now both iris and df refer to the same dataframe object and any changes done via one will reflect in other.

So effectively this is not creating another dataframe object. And if we wish to create a copy then we will use copy() function for that purpose:

df = iris.copy()

In [2]:
# first we need to import pandas as pd
import pandas as pd

In [3]:
# here we will use the iris csv dataset, you can get this dataset at the link below
# csv:each row is separated nad column is separated by commas
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
print(iris)
print(type(iris))

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>

In [5]:
# here we are making a copy of the dataset so that we can make as many changes as we want and can have different changes in different 
# files as well
df = iris.copy()

In [7]:
# return first 5 rows by default
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [11]:
# return first 4 rows
df.head(4)

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa

In [13]:
# return last 3 rows
df.tail(3)

     5.1  3.5  1.4  0.2     Iris-setosa
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [14]:
# shape tells us aboyt the shape of the dataset(149 rows and 5 columns in this case)
print(df.shape)

(149, 5)

In [15]:
# gives the information about the datatype
print(df.dtypes)

5.1            float64
3.5            float64
1.4            float64
0.2            float64
Iris-setosa     object
dtype: object

In [11]:
print(df.columns)
print()
# we can change the names of the column as well
df.columns = ['sl','sw','pl','pw','flower']
print(df.columns)

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

Index(['sl', 'sw', 'pl', 'pw', 'flower'], dtype='object')

In [24]:
# describes give syou the statistical info about the data
print(df.describe())

               sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [27]:
# return a complete column
df["sl"]

0      4.9
1      4.7
2      4.6
3      5.0
4      5.4
5      4.6
6      5.0
7      4.4
8      4.9
9      5.4
10     4.8
11     4.8
12     4.3
13     5.8
14     5.7
15     5.4
16     5.1
17     5.7
18     5.1
19     5.4
20     5.1
21     4.6
22     5.1
23     4.8
24     5.0
25     5.0
26     5.2
27     5.2
28     4.7
29     4.8
      ...
119    6.9
120    5.6
121    7.7
122    6.3
123    6.7
124    7.2
125    6.2
126    6.1
127    6.4
128    7.2
129    7.4
130    7.9
131    6.4
132    6.3
133    6.1
134    7.7
135    6.3
136    6.4
137    6.0
138    6.9
139    6.7
140    6.9
141    5.8
142    6.8
143    6.7
144    6.7
145    6.3
146    6.5
147    6.2
148    5.9
Name: sl, Length: 149, dtype: float64

In [12]:
df.flower

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17        Iris-setosa
18        Iris-setosa
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25        Iris-setosa
26        Iris-setosa
27        Iris-setosa
28        Iris-setosa
29        Iris-setosa
            ...
119    Iris-virginica
120    Iris-virginica
121    Iris-virginica
122    Iris-virginica
123    Iris-virginica
124    Iris-virginica
125    Iris-virginica
126    Iris-virginica
127    Iris-virginica
128    Iris-virginica
129    Iris-virginica
130    Iris-virginica
131    Iris-virginica
132    Iris-virginica
133    Iris-virginica
134    Iris-virginica
135    Iris-virginica
136    Iris-virginica
137    Iris-virginica
138    Iris-virginica
139    Iris-virginica
140    Iris-virginica
141    Iris-virginica
142    Iris-virginica
143    Iris-virginica
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: flower, Length: 149, dtype: object

In [33]:
df["flower"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17        Iris-setosa
18        Iris-setosa
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25        Iris-setosa
26        Iris-setosa
27        Iris-setosa
28        Iris-setosa
29        Iris-setosa
            ...
119    Iris-virginica
120    Iris-virginica
121    Iris-virginica
122    Iris-virginica
123    Iris-virginica
124    Iris-virginica
125    Iris-virginica
126    Iris-virginica
127    Iris-virginica
128    Iris-virginica
129    Iris-virginica
130    Iris-virginica
131    Iris-virginica
132    Iris-virginica
133    Iris-virginica
134    Iris-virginica
135    Iris-virginica
136    Iris-virginica
137    Iris-virginica
138    Iris-virginica
139    Iris-virginica
140    Iris-virginica
141    Iris-virginica
142    Iris-virginica
143    Iris-virginica
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: flower, Length: 149, dtype: object

In [37]:
# return the number of null entries in each column
df.isnull().sum()

sl        0
sw        0
pl        0
pw        0
flower    0
dtype: int64

In [38]:
# almost works like slicing
df.iloc[1:4,2:3]

    pl
1  1.3
2  1.5
3  1.4

In [39]:
# no change because we already have a copy as df,so no change is reflected 

df.drop(0)

      sl   sw   pl   pw          flower
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
30   5.4  3.4  1.5  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[148 rows x 5 columns]

In [40]:
# no change because we already have a copy as df,so no change is reflected 
df.head()

    sl   sw   pl   pw       flower
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [46]:
# But here you can notice that first row is dropped because now we hhave saved df.drop(0) in "a",so changes are reflected in 
# the output now
a = df.drop(0)
a.head()

    sl   sw   pl   pw       flower
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa

In [50]:
# Drop by label
# if we want change in the df itself than 'inplace = True' is used
df.drop(1 , inplace = True)
df.head()
# here 2 3 4 5 6 are labels

    sl   sw   pl   pw       flower
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa

In [8]:
df.columns
df.index
# in the output we can see that index are still still same strating from 0,so we made changes in labels, not index

RangeIndex(start=0, stop=149, step=1)

In [57]:
# so index 0 corresponds to label 2 and index 5 corresponds to label 7
df.index[0],df.index[5]

(2, 7)

In [60]:
# we can also drop a row using index instead of labels
df.drop(df.index[0])

      sl   sw   pl   pw          flower
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
30   5.4  3.4  1.5  0.4     Iris-setosa
31   5.2  4.1  1.5  0.1     Iris-setosa
32   5.5  4.2  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[146 rows x 5 columns]

In [61]:
df.head()

    sl   sw   pl   pw       flower
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa

In [62]:
# we use inplace= True to make changes in df itself
df.drop(df.index[0],inplace = True)
df.head()

    sl   sw   pl   pw       flower
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa

In [63]:
# rows at index 0 and 1 are dropped
df.drop(df.index[[0,1]],inplace = True)
df.head()

    sl   sw   pl   pw       flower
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa
8  4.9  3.1  1.5  0.1  Iris-setosa
9  5.4  3.7  1.5  0.2  Iris-setosa

In [64]:
df.drop(df.index[[0,1]],inplace = True)
df.head()

     sl   sw   pl   pw       flower
7   4.4  2.9  1.4  0.2  Iris-setosa
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa

In [66]:
df.drop(df.index[0],inplace = True)
df.head()

     sl   sw   pl   pw       flower
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa

In [69]:
# if the value in "sl" column is less than 5 than return True else false
df.sl<5

8       True
9      False
10      True
11      True
12      True
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22     False
23      True
24     False
25     False
26     False
27     False
28      True
29      True
30     False
31     False
32     False
33      True
34     False
35     False
36      True
37      True
       ...
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
Name: sl, Length: 141, dtype: bool

In [70]:
# return only the rows with values greater than 5
df[df.sl>5]

      sl   sw   pl   pw           flower
9    5.4  3.7  1.5  0.2      Iris-setosa
13   5.8  4.0  1.2  0.2      Iris-setosa
14   5.7  4.4  1.5  0.4      Iris-setosa
15   5.4  3.9  1.3  0.4      Iris-setosa
16   5.1  3.5  1.4  0.3      Iris-setosa
17   5.7  3.8  1.7  0.3      Iris-setosa
18   5.1  3.8  1.5  0.3      Iris-setosa
19   5.4  3.4  1.7  0.2      Iris-setosa
20   5.1  3.7  1.5  0.4      Iris-setosa
22   5.1  3.3  1.7  0.5      Iris-setosa
26   5.2  3.5  1.5  0.2      Iris-setosa
27   5.2  3.4  1.4  0.2      Iris-setosa
30   5.4  3.4  1.5  0.4      Iris-setosa
31   5.2  4.1  1.5  0.1      Iris-setosa
32   5.5  4.2  1.4  0.2      Iris-setosa
35   5.5  3.5  1.3  0.2      Iris-setosa
38   5.1  3.4  1.5  0.2      Iris-setosa
43   5.1  3.8  1.9  0.4      Iris-setosa
45   5.1  3.8  1.6  0.2      Iris-setosa
47   5.3  3.7  1.5  0.2      Iris-setosa
49   7.0  3.2  4.7  1.4  Iris-versicolor
50   6.4  3.2  4.5  1.5  Iris-versicolor
51   6.9  3.1  4.9  1.5  Iris-versicolor
52   5.5  2.3  4.0  1.3  Iris-versicolor
53   6.5  2.8  4.6  1.5  Iris-versicolor
54   5.7  2.8  4.5  1.3  Iris-versicolor
55   6.3  3.3  4.7  1.6  Iris-versicolor
57   6.6  2.9  4.6  1.3  Iris-versicolor
58   5.2  2.7  3.9  1.4  Iris-versicolor
60   5.9  3.0  4.2  1.5  Iris-versicolor
..   ...  ...  ...  ...              ...
119  6.9  3.2  5.7  2.3   Iris-virginica
120  5.6  2.8  4.9  2.0   Iris-virginica
121  7.7  2.8  6.7  2.0   Iris-virginica
122  6.3  2.7  4.9  1.8   Iris-virginica
123  6.7  3.3  5.7  2.1   Iris-virginica
124  7.2  3.2  6.0  1.8   Iris-virginica
125  6.2  2.8  4.8  1.8   Iris-virginica
126  6.1  3.0  4.9  1.8   Iris-virginica
127  6.4  2.8  5.6  2.1   Iris-virginica
128  7.2  3.0  5.8  1.6   Iris-virginica
129  7.4  2.8  6.1  1.9   Iris-virginica
130  7.9  3.8  6.4  2.0   Iris-virginica
131  6.4  2.8  5.6  2.2   Iris-virginica
132  6.3  2.8  5.1  1.5   Iris-virginica
133  6.1  2.6  5.6  1.4   Iris-virginica
134  7.7  3.0  6.1  2.3   Iris-virginica
135  6.3  3.4  5.6  2.4   Iris-virginica
136  6.4  3.1  5.5  1.8   Iris-virginica
137  6.0  3.0  4.8  1.8   Iris-virginica
138  6.9  3.1  5.4  2.1   Iris-virginica
139  6.7  3.1  5.6  2.4   Iris-virginica
140  6.9  3.1  5.1  2.3   Iris-virginica
141  5.8  2.7  5.1  1.9   Iris-virginica
142  6.8  3.2  5.9  2.3   Iris-virginica
143  6.7  3.3  5.7  2.5   Iris-virginica
144  6.7  3.0  5.2  2.3   Iris-virginica
145  6.3  2.5  5.0  1.9   Iris-virginica
146  6.5  3.0  5.2  2.0   Iris-virginica
147  6.2  3.4  5.4  2.3   Iris-virginica
148  5.9  3.0  5.1  1.8   Iris-virginica

[116 rows x 5 columns]

In [73]:
# return only the rows with values less than 3 in "pw" column
df[df.pw<3]

      sl   sw   pl   pw          flower
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
30   5.4  3.4  1.5  0.4     Iris-setosa
31   5.2  4.1  1.5  0.1     Iris-setosa
32   5.5  4.2  1.4  0.2     Iris-setosa
33   4.9  3.1  1.5  0.1     Iris-setosa
34   5.0  3.2  1.2  0.2     Iris-setosa
35   5.5  3.5  1.3  0.2     Iris-setosa
36   4.9  3.1  1.5  0.1     Iris-setosa
37   4.4  3.0  1.3  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[141 rows x 5 columns]

In [13]:
# describe only for 'Iris-setosa' in flower column
df[df.flower == 'Iris-setosa']
df.describe()

               sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [82]:
print(df.head())
print(df.iloc[0:3,4])

     sl   sw   pl   pw       flower
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa
8     Iris-setosa
9     Iris-setosa
10    Iris-setosa
Name: flower, dtype: object

In [83]:
# iloc takes the index as argument
print(df.iloc[8])

sl                5.1
sw                3.5
pl                1.4
pw                0.3
flower    Iris-setosa
Name: 16, dtype: object

In [87]:
# loc takes the label as argument
df.loc[8]

sl                4.9
sw                3.1
pl                1.5
pw                0.1
flower    Iris-setosa
Name: 8, dtype: object

In [90]:
df.index

Int64Index([  8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
            ...
            139, 140, 141, 142, 143, 144, 145, 146, 147, 148],
           dtype='int64', length=141)

In [91]:
# we an reset the index as well
df.reset_index()

     index   sl   sw   pl   pw          flower
0        8  4.9  3.1  1.5  0.1     Iris-setosa
1        9  5.4  3.7  1.5  0.2     Iris-setosa
2       10  4.8  3.4  1.6  0.2     Iris-setosa
3       11  4.8  3.0  1.4  0.1     Iris-setosa
4       12  4.3  3.0  1.1  0.1     Iris-setosa
5       13  5.8  4.0  1.2  0.2     Iris-setosa
6       14  5.7  4.4  1.5  0.4     Iris-setosa
7       15  5.4  3.9  1.3  0.4     Iris-setosa
8       16  5.1  3.5  1.4  0.3     Iris-setosa
9       17  5.7  3.8  1.7  0.3     Iris-setosa
10      18  5.1  3.8  1.5  0.3     Iris-setosa
11      19  5.4  3.4  1.7  0.2     Iris-setosa
12      20  5.1  3.7  1.5  0.4     Iris-setosa
13      21  4.6  3.6  1.0  0.2     Iris-setosa
14      22  5.1  3.3  1.7  0.5     Iris-setosa
15      23  4.8  3.4  1.9  0.2     Iris-setosa
16      24  5.0  3.0  1.6  0.2     Iris-setosa
17      25  5.0  3.4  1.6  0.4     Iris-setosa
18      26  5.2  3.5  1.5  0.2     Iris-setosa
19      27  5.2  3.4  1.4  0.2     Iris-setosa
20      28  4.7  3.2  1.6  0.2     Iris-setosa
21      29  4.8  3.1  1.6  0.2     Iris-setosa
22      30  5.4  3.4  1.5  0.4     Iris-setosa
23      31  5.2  4.1  1.5  0.1     Iris-setosa
24      32  5.5  4.2  1.4  0.2     Iris-setosa
25      33  4.9  3.1  1.5  0.1     Iris-setosa
26      34  5.0  3.2  1.2  0.2     Iris-setosa
27      35  5.5  3.5  1.3  0.2     Iris-setosa
28      36  4.9  3.1  1.5  0.1     Iris-setosa
29      37  4.4  3.0  1.3  0.2     Iris-setosa
..     ...  ...  ...  ...  ...             ...
111    119  6.9  3.2  5.7  2.3  Iris-virginica
112    120  5.6  2.8  4.9  2.0  Iris-virginica
113    121  7.7  2.8  6.7  2.0  Iris-virginica
114    122  6.3  2.7  4.9  1.8  Iris-virginica
115    123  6.7  3.3  5.7  2.1  Iris-virginica
116    124  7.2  3.2  6.0  1.8  Iris-virginica
117    125  6.2  2.8  4.8  1.8  Iris-virginica
118    126  6.1  3.0  4.9  1.8  Iris-virginica
119    127  6.4  2.8  5.6  2.1  Iris-virginica
120    128  7.2  3.0  5.8  1.6  Iris-virginica
121    129  7.4  2.8  6.1  1.9  Iris-virginica
122    130  7.9  3.8  6.4  2.0  Iris-virginica
123    131  6.4  2.8  5.6  2.2  Iris-virginica
124    132  6.3  2.8  5.1  1.5  Iris-virginica
125    133  6.1  2.6  5.6  1.4  Iris-virginica
126    134  7.7  3.0  6.1  2.3  Iris-virginica
127    135  6.3  3.4  5.6  2.4  Iris-virginica
128    136  6.4  3.1  5.5  1.8  Iris-virginica
129    137  6.0  3.0  4.8  1.8  Iris-virginica
130    138  6.9  3.1  5.4  2.1  Iris-virginica
131    139  6.7  3.1  5.6  2.4  Iris-virginica
132    140  6.9  3.1  5.1  2.3  Iris-virginica
133    141  5.8  2.7  5.1  1.9  Iris-virginica
134    142  6.8  3.2  5.9  2.3  Iris-virginica
135    143  6.7  3.3  5.7  2.5  Iris-virginica
136    144  6.7  3.0  5.2  2.3  Iris-virginica
137    145  6.3  2.5  5.0  1.9  Iris-virginica
138    146  6.5  3.0  5.2  2.0  Iris-virginica
139    147  6.2  3.4  5.4  2.3  Iris-virginica
140    148  5.9  3.0  5.1  1.8  Iris-virginica

[141 rows x 6 columns]

In [92]:
df.index

Int64Index([  8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
            ...
            139, 140, 141, 142, 143, 144, 145, 146, 147, 148],
           dtype='int64', length=141)

In [93]:
# to remove old column of labels and get a fresh column of index
df.reset_index(drop = True)

      sl   sw   pl   pw          flower
0    4.9  3.1  1.5  0.1     Iris-setosa
1    5.4  3.7  1.5  0.2     Iris-setosa
2    4.8  3.4  1.6  0.2     Iris-setosa
3    4.8  3.0  1.4  0.1     Iris-setosa
4    4.3  3.0  1.1  0.1     Iris-setosa
5    5.8  4.0  1.2  0.2     Iris-setosa
6    5.7  4.4  1.5  0.4     Iris-setosa
7    5.4  3.9  1.3  0.4     Iris-setosa
8    5.1  3.5  1.4  0.3     Iris-setosa
9    5.7  3.8  1.7  0.3     Iris-setosa
10   5.1  3.8  1.5  0.3     Iris-setosa
11   5.4  3.4  1.7  0.2     Iris-setosa
12   5.1  3.7  1.5  0.4     Iris-setosa
13   4.6  3.6  1.0  0.2     Iris-setosa
14   5.1  3.3  1.7  0.5     Iris-setosa
15   4.8  3.4  1.9  0.2     Iris-setosa
16   5.0  3.0  1.6  0.2     Iris-setosa
17   5.0  3.4  1.6  0.4     Iris-setosa
18   5.2  3.5  1.5  0.2     Iris-setosa
19   5.2  3.4  1.4  0.2     Iris-setosa
20   4.7  3.2  1.6  0.2     Iris-setosa
21   4.8  3.1  1.6  0.2     Iris-setosa
22   5.4  3.4  1.5  0.4     Iris-setosa
23   5.2  4.1  1.5  0.1     Iris-setosa
24   5.5  4.2  1.4  0.2     Iris-setosa
25   4.9  3.1  1.5  0.1     Iris-setosa
26   5.0  3.2  1.2  0.2     Iris-setosa
27   5.5  3.5  1.3  0.2     Iris-setosa
28   4.9  3.1  1.5  0.1     Iris-setosa
29   4.4  3.0  1.3  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
111  6.9  3.2  5.7  2.3  Iris-virginica
112  5.6  2.8  4.9  2.0  Iris-virginica
113  7.7  2.8  6.7  2.0  Iris-virginica
114  6.3  2.7  4.9  1.8  Iris-virginica
115  6.7  3.3  5.7  2.1  Iris-virginica
116  7.2  3.2  6.0  1.8  Iris-virginica
117  6.2  2.8  4.8  1.8  Iris-virginica
118  6.1  3.0  4.9  1.8  Iris-virginica
119  6.4  2.8  5.6  2.1  Iris-virginica
120  7.2  3.0  5.8  1.6  Iris-virginica
121  7.4  2.8  6.1  1.9  Iris-virginica
122  7.9  3.8  6.4  2.0  Iris-virginica
123  6.4  2.8  5.6  2.2  Iris-virginica
124  6.3  2.8  5.1  1.5  Iris-virginica
125  6.1  2.6  5.6  1.4  Iris-virginica
126  7.7  3.0  6.1  2.3  Iris-virginica
127  6.3  3.4  5.6  2.4  Iris-virginica
128  6.4  3.1  5.5  1.8  Iris-virginica
129  6.0  3.0  4.8  1.8  Iris-virginica
130  6.9  3.1  5.4  2.1  Iris-virginica
131  6.7  3.1  5.6  2.4  Iris-virginica
132  6.9  3.1  5.1  2.3  Iris-virginica
133  5.8  2.7  5.1  1.9  Iris-virginica
134  6.8  3.2  5.9  2.3  Iris-virginica
135  6.7  3.3  5.7  2.5  Iris-virginica
136  6.7  3.0  5.2  2.3  Iris-virginica
137  6.3  2.5  5.0  1.9  Iris-virginica
138  6.5  3.0  5.2  2.0  Iris-virginica
139  6.2  3.4  5.4  2.3  Iris-virginica
140  5.9  3.0  5.1  1.8  Iris-virginica

[141 rows x 5 columns]

In [96]:
# to make changes in df itself
df.reset_index(drop = True,inplace = True)
df.index

RangeIndex(start=0, stop=141, step=1)

In [112]:
# deleting a column
df.drop('pw',axis = 1,inplace = True)
df.head()

    pl       flower
0  1.5  Iris-setosa
1  1.5  Iris-setosa
2  1.6  Iris-setosa
3  1.4  Iris-setosa
4  1.1  Iris-setosa

In [114]:
# we can make a new copy of iris so as to get all the data back
df = iris.copy()
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [115]:
df.columns = ['sl','sw','pl','pw','flower']
df.columns

Index(['sl', 'sw', 'pl', 'pw', 'flower'], dtype='object')

In [117]:
# Same as the initial data we started with
df.head()

    sl   sw   pl   pw       flower
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [118]:
# adding a column "diff_pl-pw" that gives the difference of "pl" and "pw"
df["diff_pl_pw"] = df["pl"]-df["pw"]
df.tail()

      sl   sw   pl   pw          flower  diff_pl_pw
144  6.7  3.0  5.2  2.3  Iris-virginica         2.9
145  6.3  2.5  5.0  1.9  Iris-virginica         3.1
146  6.5  3.0  5.2  2.0  Iris-virginica         3.2
147  6.2  3.4  5.4  2.3  Iris-virginica         3.1
148  5.9  3.0  5.1  1.8  Iris-virginica         3.3

In [123]:
df["diff of sl and sw"] = df["sl"] - df["sw"]
df.tail()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
144,6.7,3.0,5.2,2.3,Iris-virginica,2.9,3.7,1,3.7
145,6.3,2.5,5.0,1.9,Iris-virginica,3.1,3.8,1,3.8
146,6.5,3.0,5.2,2.0,Iris-virginica,3.2,3.5,1,3.5
147,6.2,3.4,5.4,2.3,Iris-virginica,3.1,2.8,1,2.8
148,5.9,3.0,5.1,1.8,Iris-virginica,3.3,2.9,1,2.9

In [124]:
# adding a new column with value as '1'
df["abc"] = 1
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
2,4.6,3.1,1.5,0.2,Iris-setosa,1.3,1.5,1,1.5
3,5.0,3.6,1.4,0.2,Iris-setosa,1.2,1.4,1,1.4
4,5.4,3.9,1.7,0.4,Iris-setosa,1.3,1.5,1,1.5

In [125]:
df["pl"] - df["pw"]
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
2,4.6,3.1,1.5,0.2,Iris-setosa,1.3,1.5,1,1.5
3,5.0,3.6,1.4,0.2,Iris-setosa,1.2,1.4,1,1.4
4,5.4,3.9,1.7,0.4,Iris-setosa,1.3,1.5,1,1.5

In [132]:
# giving '0' as the value to the positions given in iloc
df.iloc[2:4 , 1:3] = 0
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
2,4.6,0.0,0.0,0.2,Iris-setosa,1.3,1.5,1,1.5
3,5.0,0.0,0.0,0.2,Iris-setosa,1.2,1.4,1,1.4
4,5.4,3.9,1.7,0.4,Iris-setosa,1.3,1.5,1,1.5

In [134]:
import numpy as np
# giving 'np.nan' as the value to the positions given in iloc
df.iloc[2:4 , 1:3] = np.nan
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
2,4.6,NaN,NaN,0.2,Iris-setosa,1.3,1.5,1,1.5
3,5.0,NaN,NaN,0.2,Iris-setosa,1.2,1.4,1,1.4
4,5.4,3.9,1.7,0.4,Iris-setosa,1.3,1.5,1,1.5

In [135]:
df.describe()

,sl,sw,pl,pw,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
count,149.000000,147.000000,147.000000,149.000000,149.000000,149.000000,149.0,149.000000
mean,5.848322,3.046939,3.806122,1.205369,2.569128,2.797315,1.0,2.797315
std,0.828594,0.434048,1.750351,0.761292,1.047707,0.974190,0.0,0.974190
min,4.300000,2.000000,1.000000,0.100000,0.800000,1.000000,1.0,1.000000
25%,5.100000,2.800000,1.600000,0.300000,1.400000,1.800000,1.0,1.800000
50%,5.800000,3.000000,4.400000,1.300000,2.900000,3.000000,1.0,3.000000
75%,6.400000,3.300000,5.100000,1.800000,3.300000,3.600000,1.0,3.600000
max,7.900000,4.400000,6.900000,2.500000,4.700000,5.100000,1.0,5.100000

In [140]:
# drops the row with 2 and 3 labels because they have Nan values
df.dropna()
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
4,5.4,3.9,1.7,0.4,Iris-setosa,1.3,1.5,1,1.5
5,4.6,3.4,1.4,0.3,Iris-setosa,1.1,1.2,1,1.2
6,5.0,3.4,1.5,0.2,Iris-setosa,1.3,1.6,1,1.6

In [137]:
# to make changes in df itself
df.dropna(inplace = True)
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
4,5.4,3.9,1.7,0.4,Iris-setosa,1.3,1.5,1,1.5
5,4.6,3.4,1.4,0.3,Iris-setosa,1.1,1.2,1,1.2
6,5.0,3.4,1.5,0.2,Iris-setosa,1.3,1.6,1,1.6

In [142]:
df.iloc[2:4,1:3] = np.nan
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
4,5.4,NaN,NaN,0.4,Iris-setosa,1.3,1.5,1,1.5
5,4.6,NaN,NaN,0.3,Iris-setosa,1.1,1.2,1,1.2
6,5.0,3.4,1.5,0.2,Iris-setosa,1.3,1.6,1,1.6

In [143]:
df.dropna()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
6,5.0,3.4,1.5,0.2,Iris-setosa,1.3,1.6,1,1.6
7,4.4,2.9,1.4,0.2,Iris-setosa,1.2,1.5,1,1.5
8,4.9,3.1,1.5,0.1,Iris-setosa,1.4,1.8,1,1.8
9,5.4,3.7,1.5,0.2,Iris-setosa,1.3,1.7,1,1.7
10,4.8,3.4,1.6,0.2,Iris-setosa,1.4,1.4,1,1.4
11,4.8,3.0,1.4,0.1,Iris-setosa,1.3,1.8,1,1.8
12,4.3,3.0,1.1,0.1,Iris-setosa,1.0,1.3,1,1.3
13,5.8,4.0,1.2,0.2,Iris-setosa,1.0,1.8,1,1.8
14,5.7,4.4,1.5,0.4,Iris-setosa,1.1,1.3,1,1.3
15,5.4,3.9,1.3,0.4,Iris-setosa,0.9,1.5,1,1.5
16,5.1,3.5,1.4,0.3,Iris-setosa,1.1,1.6,1,1.6
17,5.7,3.8,1.7,0.3,Iris-setosa,1.4,1.9,1,1.9
18,5.1,3.8,1.5,0.3,Iris-setosa,1.2,1.3,1,1.3
19,5.4,3.4,1.7,0.2,Iris-setosa,1.5,2.0,1,2.0
20,5.1,3.7,1.5,0.4,Iris-setosa,1.1,1.4,1,1.4
21,4.6,3.6,1.0,0.2,Iris-setosa,0.8,1.0,1,1.0
22,5.1,3.3,1.7,0.5,Iris-setosa,1.2,1.8,1,1.8
23,4.8,3.4,1.9,0.2,Iris-setosa,1.7,1.4,1,1.4
24,5.0,3.0,1.6,0.2,Iris-setosa,1.4,2.0,1,2.0
25,5.0,3.4,1.6,0.4,Iris-setosa,1.2,1.6,1,1.6
26,5.2,3.5,1.5,0.2,Iris-setosa,1.3,1.7,1,1.7
27,5.2,3.4,1.4,0.2,Iris-setosa,1.2,1.8,1,1.8
28,4.7,3.2,1.6,0.2,Iris-setosa,1.4,1.5,1,1.5
29,4.8,3.1,1.6,0.2,Iris-setosa,1.4,1.7,1,1.7
30,5.4,3.4,1.5,0.4,Iris-setosa,1.1,2.0,1,2.0
31,5.2,4.1,1.5,0.1,Iris-setosa,1.4,1.1,1,1.1
32,5.5,4.2,1.4,0.2,Iris-setosa,1.2,1.3,1,1.3
33,4.9,3.1,1.5,0.1,Iris-setosa,1.4,1.8,1,1.8
...,...,...,...,...,...,...,...,...,...
119,6.9,3.2,5.7,2.3,Iris-virginica,3.4,3.7,1,3.7
120,5.6,2.8,4.9,2.0,Iris-virginica,2.9,2.8,1,2.8
121,7.7,2.8,6.7,2.0,Iris-virginica,4.7,4.9,1,4.9
122,6.3,2.7,4.9,1.8,Iris-virginica,3.1,3.6,1,3.6
123,6.7,3.3,5.7,2.1,Iris-virginica,3.6,3.4,1,3.4
124,7.2,3.2,6.0,1.8,Iris-virginica,4.2,4.0,1,4.0
125,6.2,2.8,4.8,1.8,Iris-virginica,3.0,3.4,1,3.4
126,6.1,3.0,4.9,1.8,Iris-virginica,3.1,3.1,1,3.1
127,6.4,2.8,5.6,2.1,Iris-virginica,3.5,3.6,1,3.6
128,7.2,3.0,5.8,1.6,Iris-virginica,4.2,4.2,1,4.2
129,7.4,2.8,6.1,1.9,Iris-virginica,4.2,4.6,1,4.6
130,7.9,3.8,6.4,2.0,Iris-virginica,4.4,4.1,1,4.1
131,6.4,2.8,5.6,2.2,Iris-virginica,3.4,3.6,1,3.6
132,6.3,2.8,5.1,1.5,Iris-virginica,3.6,3.5,1,3.5
133,6.1,2.6,5.6,1.4,Iris-virginica,4.2,3.5,1,3.5
134,7.7,3.0,6.1,2.3,Iris-virginica,3.8,4.7,1,4.7
135,6.3,3.4,5.6,2.4,Iris-virginica,3.2,2.9,1,2.9
136,6.4,3.1,5.5,1.8,Iris-virginica,3.7,3.3,1,3.3
137,6.0,3.0,4.8,1.8,Iris-virginica,3.0,3.0,1,3.0
138,6.9,3.1,5.4,2.1,Iris-virginica,3.3,3.8,1,3.8
139,6.7,3.1,5.6,2.4,Iris-virginica,3.2,3.6,1,3.6
140,6.9,3.1,5.1,2.3,Iris-virginica,2.8,3.8,1,3.8
141,5.8,2.7,5.1,1.9,Iris-virginica,3.2,3.1,1,3.1
142,6.8,3.2,5.9,2.3,Iris-virginica,3.6,3.6,1,3.6
143,6.7,3.3,5.7,2.5,Iris-virginica,3.2,3.4,1,3.4
144,6.7,3.0,5.2,2.3,Iris-virginica,2.9,3.7,1,3.7
145,6.3,2.5,5.0,1.9,Iris-virginica,3.1,3.8,1,3.8
146,6.5,3.0,5.2,2.0,Iris-virginica,3.2,3.5,1,3.5
147,6.2,3.4,5.4,2.3,Iris-virginica,3.1,2.8,1,2.8
148,5.9,3.0,5.1,1.8,Iris-virginica,3.3,2.9,1,2.9

In [144]:
df.drop(145)

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
4,5.4,NaN,NaN,0.4,Iris-setosa,1.3,1.5,1,1.5
5,4.6,NaN,NaN,0.3,Iris-setosa,1.1,1.2,1,1.2
6,5.0,3.4,1.5,0.2,Iris-setosa,1.3,1.6,1,1.6
7,4.4,2.9,1.4,0.2,Iris-setosa,1.2,1.5,1,1.5
8,4.9,3.1,1.5,0.1,Iris-setosa,1.4,1.8,1,1.8
9,5.4,3.7,1.5,0.2,Iris-setosa,1.3,1.7,1,1.7
10,4.8,3.4,1.6,0.2,Iris-setosa,1.4,1.4,1,1.4
11,4.8,3.0,1.4,0.1,Iris-setosa,1.3,1.8,1,1.8
12,4.3,3.0,1.1,0.1,Iris-setosa,1.0,1.3,1,1.3
13,5.8,4.0,1.2,0.2,Iris-setosa,1.0,1.8,1,1.8
14,5.7,4.4,1.5,0.4,Iris-setosa,1.1,1.3,1,1.3
15,5.4,3.9,1.3,0.4,Iris-setosa,0.9,1.5,1,1.5
16,5.1,3.5,1.4,0.3,Iris-setosa,1.1,1.6,1,1.6
17,5.7,3.8,1.7,0.3,Iris-setosa,1.4,1.9,1,1.9
18,5.1,3.8,1.5,0.3,Iris-setosa,1.2,1.3,1,1.3
19,5.4,3.4,1.7,0.2,Iris-setosa,1.5,2.0,1,2.0
20,5.1,3.7,1.5,0.4,Iris-setosa,1.1,1.4,1,1.4
21,4.6,3.6,1.0,0.2,Iris-setosa,0.8,1.0,1,1.0
22,5.1,3.3,1.7,0.5,Iris-setosa,1.2,1.8,1,1.8
23,4.8,3.4,1.9,0.2,Iris-setosa,1.7,1.4,1,1.4
24,5.0,3.0,1.6,0.2,Iris-setosa,1.4,2.0,1,2.0
25,5.0,3.4,1.6,0.4,Iris-setosa,1.2,1.6,1,1.6
26,5.2,3.5,1.5,0.2,Iris-setosa,1.3,1.7,1,1.7
27,5.2,3.4,1.4,0.2,Iris-setosa,1.2,1.8,1,1.8
28,4.7,3.2,1.6,0.2,Iris-setosa,1.4,1.5,1,1.5
29,4.8,3.1,1.6,0.2,Iris-setosa,1.4,1.7,1,1.7
30,5.4,3.4,1.5,0.4,Iris-setosa,1.1,2.0,1,2.0
31,5.2,4.1,1.5,0.1,Iris-setosa,1.4,1.1,1,1.1
...,...,...,...,...,...,...,...,...,...
118,6.0,2.2,5.0,1.5,Iris-virginica,3.5,3.8,1,3.8
119,6.9,3.2,5.7,2.3,Iris-virginica,3.4,3.7,1,3.7
120,5.6,2.8,4.9,2.0,Iris-virginica,2.9,2.8,1,2.8
121,7.7,2.8,6.7,2.0,Iris-virginica,4.7,4.9,1,4.9
122,6.3,2.7,4.9,1.8,Iris-virginica,3.1,3.6,1,3.6
123,6.7,3.3,5.7,2.1,Iris-virginica,3.6,3.4,1,3.4
124,7.2,3.2,6.0,1.8,Iris-virginica,4.2,4.0,1,4.0
125,6.2,2.8,4.8,1.8,Iris-virginica,3.0,3.4,1,3.4
126,6.1,3.0,4.9,1.8,Iris-virginica,3.1,3.1,1,3.1
127,6.4,2.8,5.6,2.1,Iris-virginica,3.5,3.6,1,3.6
128,7.2,3.0,5.8,1.6,Iris-virginica,4.2,4.2,1,4.2
129,7.4,2.8,6.1,1.9,Iris-virginica,4.2,4.6,1,4.6
130,7.9,3.8,6.4,2.0,Iris-virginica,4.4,4.1,1,4.1
131,6.4,2.8,5.6,2.2,Iris-virginica,3.4,3.6,1,3.6
132,6.3,2.8,5.1,1.5,Iris-virginica,3.6,3.5,1,3.5
133,6.1,2.6,5.6,1.4,Iris-virginica,4.2,3.5,1,3.5
134,7.7,3.0,6.1,2.3,Iris-virginica,3.8,4.7,1,4.7
135,6.3,3.4,5.6,2.4,Iris-virginica,3.2,2.9,1,2.9
136,6.4,3.1,5.5,1.8,Iris-virginica,3.7,3.3,1,3.3
137,6.0,3.0,4.8,1.8,Iris-virginica,3.0,3.0,1,3.0
138,6.9,3.1,5.4,2.1,Iris-virginica,3.3,3.8,1,3.8
139,6.7,3.1,5.6,2.4,Iris-virginica,3.2,3.6,1,3.6
140,6.9,3.1,5.1,2.3,Iris-virginica,2.8,3.8,1,3.8
141,5.8,2.7,5.1,1.9,Iris-virginica,3.2,3.1,1,3.1
142,6.8,3.2,5.9,2.3,Iris-virginica,3.6,3.6,1,3.6
143,6.7,3.3,5.7,2.5,Iris-virginica,3.2,3.4,1,3.4
144,6.7,3.0,5.2,2.3,Iris-virginica,2.9,3.7,1,3.7
146,6.5,3.0,5.2,2.0,Iris-virginica,3.2,3.5,1,3.5
147,6.2,3.4,5.4,2.3,Iris-virginica,3.1,2.8,1,2.8
148,5.9,3.0,5.1,1.8,Iris-virginica,3.3,2.9,1,2.9

In [147]:
# if there is Nan in the dataset and we want to fill it with the mean of the values in "sw" column
# since we have not used inplace,changes are not reflected in the output
df.sw.fillna(df.sw.mean())
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.0,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.2,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
4,5.4,NaN,NaN,0.4,Iris-setosa,1.3,1.5,1,1.5
5,4.6,NaN,NaN,0.3,Iris-setosa,1.1,1.2,1,1.2
6,5.0,3.4,1.5,0.2,Iris-setosa,1.3,1.6,1,1.6

In [149]:
# changes are rlected when we use inplace= True
df.sw.fillna((df.sw.mean()),inplace = True)
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.000000,1.4,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.200000,1.3,0.2,Iris-setosa,1.1,1.5,1,1.5
4,5.4,3.038621,NaN,0.4,Iris-setosa,1.3,1.5,1,1.5
5,4.6,3.038621,NaN,0.3,Iris-setosa,1.1,1.2,1,1.2
6,5.0,3.400000,1.5,0.2,Iris-setosa,1.3,1.6,1,1.6

In [151]:
# same we will do with "pl" column
df.pl.fillna((df.pl.mean()),inplace = True)
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw
0,4.9,3.000000,1.400000,0.2,Iris-setosa,1.2,1.9,1,1.9
1,4.7,3.200000,1.300000,0.2,Iris-setosa,1.1,1.5,1,1.5
4,5.4,3.038621,3.837241,0.4,Iris-setosa,1.3,1.5,1,1.5
5,4.6,3.038621,3.837241,0.3,Iris-setosa,1.1,1.2,1,1.2
6,5.0,3.400000,1.500000,0.2,Iris-setosa,1.3,1.6,1,1.6

In [152]:
# adding a new column as "gender"
df["Gender"] = "Female"
df.head()

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw,Gender
0,4.9,3.000000,1.400000,0.2,Iris-setosa,1.2,1.9,1,1.9,Female
1,4.7,3.200000,1.300000,0.2,Iris-setosa,1.1,1.5,1,1.5,Female
4,5.4,3.038621,3.837241,0.4,Iris-setosa,1.3,1.5,1,1.5,Female
5,4.6,3.038621,3.837241,0.3,Iris-setosa,1.1,1.2,1,1.2,Female
6,5.0,3.400000,1.500000,0.2,Iris-setosa,1.3,1.6,1,1.6,Female

In [155]:
# Replacing values with Male
df.iloc[0:10 , 6] = "Male"
df.head(11)

,sl,sw,pl,pw,flower,diff_pl_pw,diff_sl_sw,abc,diff of sl and sw,Gender
0,4.9,3.000000,1.400000,0.2,Iris-setosa,1.2,Male,1,1.9,Female
1,4.7,3.200000,1.300000,0.2,Iris-setosa,1.1,Male,1,1.5,Female
4,5.4,3.038621,3.837241,0.4,Iris-setosa,1.3,Male,1,1.5,Female
5,4.6,3.038621,3.837241,0.3,Iris-setosa,1.1,Male,1,1.2,Female
6,5.0,3.400000,1.500000,0.2,Iris-setosa,1.3,Male,1,1.6,Female
7,4.4,2.900000,1.400000,0.2,Iris-setosa,1.2,Male,1,1.5,Female
8,4.9,3.100000,1.500000,0.1,Iris-setosa,1.4,Male,1,1.8,Female
9,5.4,3.700000,1.500000,0.2,Iris-setosa,1.3,Male,1,1.7,Female
10,4.8,3.400000,1.600000,0.2,Iris-setosa,1.4,Male,1,1.4,Female
11,4.8,3.000000,1.400000,0.1,Iris-setosa,1.3,Male,1,1.8,Female
12,4.3,3.000000,1.100000,0.1,Iris-setosa,1.0,1.3,1,1.3,Female